Repository hywenklis/buddy-api, pull requests merged in 2024-08, with the labels that each got.

#79 Chore: melhorar as configurações de qualidade do código
  .github/workflows/codeql.yml
  build.gradle
  src/main/java/com/buddy/api/domains/adoption/enums/AdoptionStatus.java
  src/main/java/com/buddy/api/domains/adoption/repositories/AdoptionRequestRepository.java
  src/main/java/com/buddy/api/domains/configuration/annotations/validators/UniqueValidator.java
  src/main/java/com/buddy/api/domains/configuration/swagger/SwaggerApiConfig.java
  src/main/java/com/buddy/api/domains/exceptions/NotFoundException.java
  src/main/java/com/buddy/api/domains/pet/dtos/PetImageDto.java
  src/main/java/com/buddy/api/domains/pet/mappers/PetDomainMapper.java
  src/main/java/com/buddy/api/domains/pet/repositories/PetImageRepository.java
  src/main/java/com/buddy/api/domains/pet/repositories/PetRepository.java
  src/main/java/com/buddy/api/domains/pet/services/impls/CreatePetImpl.java
  src/main/java/com/buddy/api/domains/pet/services/impls/FindPetImpl.java
  src/main/java/com/buddy/api/domains/shelter/dtos/ShelterCompactDto.java
  src/main/java/com/buddy/api/domains/shelter/repositories/ShelterRepository.java
  src/main/java/com/buddy/api/domains/specifications/PetSpecifications.java
  src/main/java/com/buddy/api/web/advice/controller/ErrorHandler.java
  src/main/java/com/buddy/api/web/pets/controllers/CreatePetController.java
  src/main/java/com/buddy/api/web/pets/controllers/FindPetController.java
  src/main/java/com/buddy/api/web/pets/mappers/PetMapperParamsResponse.java
  src/main/java/com/buddy/api/web/pets/requests/PetImageRequest.java
  src/main/java/com/buddy/api/web/pets/requests/PetRequest.java
  src/main/java/com/buddy/api/web/pets/requests/PetSearchCriteriaRequest.java
  src/main/java/com/buddy/api/web/pets/responses/PetImageResponse.java
  src/main/java/com/buddy/api/web/pets/responses/PetResponse.java
  src/main/java/com/buddy/api/web/shelter/controllers/CreateShelterController.java
  src/main/java/com/buddy/api/web/shelter/mappers/ShelterMapperResponse.java
  src/main/java/com/buddy/api/web/shelter/responses/ShelterResponseCompact.java
  src/main/resources/application-local.yml
  src/test/java/com/buddy/api/builders/pet/PetBuilder.java
  src/test/java/com/buddy/api/builders/pet/PetImageBuilder.java
  src/test/java/com/buddy/api/builders/shelter/ShelterBuilder.java
  src/test/java/com/buddy/api/components/PetComponent.java
  src/test/java/com/buddy/api/components/ShelterComponent.java
  src/test/java/com/buddy/api/integrations/web/pet/controller/CreatePetControllerTest.java
  src/test/java/com/buddy/api/integrations/web/shelter/controller/CreateShelterControllerTest.java
  src/test/java/com/buddy/api/units/UnitTestAbstract.java
  src/test/java/com/buddy/api/units/domains/annotations/validators/UniqueValidatorTest.java
  src/test/java/com/buddy/api/units/domains/services/impls/CreatePetTest.java
  src/test/java/com/buddy/api/units/domains/services/impls/CreateShelterTest.java
  src/test/java/com/buddy/api/units/domains/services/impls/FindShelterTest.java
Labels: enhancement

#64 fix: changes test name for clarity
  src/test/java/com/buddy/api/integrations/web/pet/controller/CreatePetControllerTest.java
Labels: enhancement

#84 Aprimoramento da configuração do Dependabot (#82)
  .github/dependabot.yml
  .github/workflows/ci-build-tests.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/scorecards.yml
  build.gradle
Labels: enhancement

#90 Fix/sort createdate tests
  src/main/java/com/buddy/api/domains/page/PageableBuilder.java
  src/test/java/com/buddy/api/components/PetComponentBuilder.java
  src/test/java/com/buddy/api/integrations/IntegrationTestAbstract.java
  src/test/java/com/buddy/api/integrations/web/pet/controller/FindPetControllerTest.java
  src/test/java/com/buddy/api/units/UnitTestAbstract.java
  src/test/java/com/buddy/api/units/domains/page/PageableBuilderTest.java
Labels: enhancement

#85 fix #48: Corrige problema de classificação por data de criação no endpoint Pet
  src/main/java/com/buddy/api/domains/adoption/entities/AdoptionRequestEntity.java
  src/main/java/com/buddy/api/domains/exceptions/NotFoundException.java
  src/main/java/com/buddy/api/domains/exceptions/PetSearchException.java
  src/main/java/com/buddy/api/domains/page/PageableBuilder.java
  src/main/java/com/buddy/api/domains/pet/entities/PetEntity.java
  src/main/java/com/buddy/api/domains/pet/entities/PetImageEntity.java
  src/main/java/com/buddy/api/domains/pet/repositories/PetRepository.java
  src/main/java/com/buddy/api/domains/pet/services/FindPet.java
  src/main/java/com/buddy/api/domains/pet/services/impls/FindPetImpl.java
  src/main/java/com/buddy/api/domains/shelter/entities/ShelterEntity.java
  src/main/java/com/buddy/api/web/advice/controller/ErrorHandler.java
  src/main/java/com/buddy/api/web/pets/controllers/FindPetController.java
  src/main/resources/application-local.yml
  src/test/java/com/buddy/api/components/PetComponentBuilder.java
  src/test/java/com/buddy/api/integrations/IntegrationTestAbstract.java
  src/test/java/com/buddy/api/integrations/web/pet/controller/FindPetControllerTest.java
  src/test/java/com/buddy/api/integrations/web/shelter/controller/CreateShelterControllerTest.java
  src/test/java/com/buddy/api/units/UnitTestAbstract.java
  src/test/java/com/buddy/api/units/domains/page/PageableBuilderTest.java
Labels: bug

#86 chore: adiciona regra para utilizar final em parametros de metodos
  config/checkstyle/checkstyle.xml
  src/main/java/com/buddy/api/BuddyApplication.java
  src/main/java/com/buddy/api/domains/configuration/annotations/validators/UniqueValidator.java
  src/main/java/com/buddy/api/domains/configuration/swagger/SwaggerApiConfig.java
  src/main/java/com/buddy/api/domains/enums/AgeRange.java
  src/main/java/com/buddy/api/domains/enums/Gender.java
  src/main/java/com/buddy/api/domains/enums/Species.java
  src/main/java/com/buddy/api/domains/enums/WeightRange.java
  src/main/java/com/buddy/api/domains/exceptions/NotFoundException.java
  src/main/java/com/buddy/api/domains/exceptions/PetSearchException.java
  src/main/java/com/buddy/api/domains/page/PageableBuilder.java
  src/main/java/com/buddy/api/domains/shelter/dtos/ShelterDto.java
  src/main/java/com/buddy/api/domains/specifications/PetSpecifications.java
  src/main/java/com/buddy/api/web/advice/controller/ErrorHandler.java
  src/main/java/com/buddy/api/web/pets/controllers/CreatePetController.java
  src/main/java/com/buddy/api/web/pets/controllers/FindPetController.java
  src/main/java/com/buddy/api/web/shelter/controllers/CreateShelterController.java
  src/test/java/com/buddy/api/builders/pet/PetBuilder.java
  src/test/java/com/buddy/api/builders/pet/PetImageBuilder.java
  src/test/java/com/buddy/api/builders/shelter/ShelterBuilder.java
  src/test/java/com/buddy/api/components/PetComponent.java
  src/test/java/com/buddy/api/components/PetComponentBuilder.java
  src/test/java/com/buddy/api/components/ShelterComponent.java
  src/test/java/com/buddy/api/units/domains/annotations/validators/UniqueValidatorTest.java
  src/test/java/com/buddy/api/units/domains/page/PageableBuilderTest.java
  src/test/java/com/buddy/api/utils/RandomCpfUtils.java
Labels: enhancement

#87 Documentação da arquitetura: Organização de pacotes e modelagem do banco de dados
  src/main/java/com/buddy/api/commons/configuration/annotations/Unique.java
  src/main/java/com/buddy/api/commons/configuration/annotations/validators/UniqueValidator.java
  src/main/java/com/buddy/api/commons/configuration/security/GlobalCorsConfig.java
  src/main/java/com/buddy/api/commons/configuration/swagger/SwaggerApiConfig.java
  src/main/java/com/buddy/api/commons/enums/AgeRange.java
  src/main/java/com/buddy/api/commons/enums/Gender.java
  src/main/java/com/buddy/api/commons/enums/Species.java
  src/main/java/com/buddy/api/commons/enums/UniqueType.java
  src/main/java/com/buddy/api/commons/enums/WeightRange.java
  src/main/java/com/buddy/api/commons/exceptions/NotFoundException.java
  src/main/java/com/buddy/api/commons/exceptions/PetSearchException.java
  src/main/java/com/buddy/api/commons/page/PageableBuilder.java
  src/main/java/com/buddy/api/domains/pet/services/impls/CreatePetImpl.java
  src/main/java/com/buddy/api/domains/pet/services/impls/FindPetImpl.java
  src/main/java/com/buddy/api/domains/pet/specifications/PetSpecifications.java
  src/main/java/com/buddy/api/web/advice/controller/ErrorHandler.java
  src/main/java/com/buddy/api/web/shelter/requests/ShelterRequest.java
  src/test/java/com/buddy/api/units/domains/annotations/validators/UniqueValidatorTest.java
  src/test/java/com/buddy/api/units/domains/page/PageableBuilderTest.java
  src/test/java/com/buddy/api/units/domains/services/impls/CreatePetTest.java
Labels: documentation
